version: "3"
services:
  nginx:
    ports:
      - "80:80" # nginx is listening on port 80. We can access it via 80 outside.
  node-app:
    build:
      context: ./api # specify location of Dockerfile
      args:
        NODE_ENV: production # Pass in the env that is used in Dockerfile later.
    environment:
      - NODE_ENV=production
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - SESSION_SECRET=${SESSION_SECRET} # password for your redis sessions
    command: node index.js # same as Dockerfile.
  mongo:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
