version: "3"
services:
    nginx:
        ports: 
            - "80:80" # nginx is listening on port 80. We can access it via 80 outside.
    node-app:
        build:
            context: . # specify location of Dockerfile
            args:
                NODE_ENV: production # Pass in the env that is used in Dockerfile later. 
        environment:
            - NODE_ENV=production
        command: node index.js # same as Dockerfile.